compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
downcast_bf16: 'no'
gpu_ids: '0,1,2,3,4'
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16' # BF16 worked before
num_machines: 1
num_processes: 5
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
debug: false
deepspeed_config:
  zero_stage: 2
  offload_optimizer_device: cpu
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: false
