compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config_file: deepspeed_config.json
downcast_bf16: 'no'
gpu_ids: '0,1,2,3,4'
machine_rank: 0
main_training_function: main
mixed_precision: 'fp16'
num_machines: 1
num_processes: 5
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
zero_stage: 2
